# Theme configuration
remote_theme: mmistakes/minimal-mistakes

# Default layout for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

