title: Nour Saad
description: >-
  A glimpse into my academic and technical journey through projects in molecular modeling, data science, scripting, and database systems.
email: nour.saad06@lau.edu
github_username: NourSaadd

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# Layout
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Enable navigation bar
header:
  nav: main
atom_feed:
  hide: true

footer:
  links: []  
  custom: footer_custom

include:
  - _pages


