remote_theme: mmistakes/minimal-mistakes

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Enable nav from _data/navigation.yml
header:
  nav: "main"
