title: Nour Saad
description: >-
  A glimpse into my academic and technical journey through projects in molecular modeling, data science, scripting, and database systems.
email: nour.saad06@lau.edu
github_username: NourSaadd

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# Layout
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Enable navigation bar
header:
  nav: main
  
footer:
  links: []  # optional: clears social or nav links
  copyright: true  # keeps your copyright line
  powered_by: false  # hides "Powered by Jekyll & Minimal Mistakes"


include:
  - _pages


